# Generated by Django 2.0.13 on 2019-04-24 15:17

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to=upload.models.content_file_name)),
                ('place', models.CharField(blank=True, max_length=125)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('size', models.BigIntegerField(blank=True)),
            ],
        ),
    ]
