# Generated by Django 2.0.13 on 2019-04-22 17:25

import upload.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to=upload.models.content_file_name)),
                ('place', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('size', models.BigIntegerField()),
            ],
        ),
    ]
