# Generated by Django 2.0.13 on 2019-04-24 21:05

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата загрузки'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(blank=True, upload_to=upload.models.content_file_name, verbose_name='картинка'),
        ),
        migrations.AlterField(
            model_name='image',
            name='place',
            field=models.CharField(blank=True, max_length=125, verbose_name='путь'),
        ),
        migrations.AlterField(
            model_name='image',
            name='size',
            field=models.BigIntegerField(blank=True, verbose_name='размер в килобайтах'),
        ),
    ]
