FROM python:3.6.8-stretch
MAINTAINER  Asadov Ahmed <zoxon470@gmail.com>

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV TZ=UTC

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get -y update \
  && apt-get install -y gettext \
    tzdata \
    nano

WORKDIR /app

COPY Pipfile Pipfile.lock ./
RUN pip install pipenv
RUN pipenv install --system --dev

COPY ./docker/django/start-dev.sh /start-dev.sh
RUN chmod +x /start-dev.sh

COPY . .

EXPOSE 8000
